// import mongoose libary
const mongoose = require('mongoose');

/**
 * a schema is the representation of an item (User, Deck, etc...) in the db. Each object is given data type and addition attributes
 * such as the minimum or maximum number of characters an object may have
 * Each object has an object id generated by mongo. Programmer may specify the _id of an object as in line 36
 */
const UserSchema = mongoose.Schema({
    username: {
        type: String,
        required: true,
        max: 99,
        min: 6
    },
    email: {
        type: String,
        required: true,
        max: 255,
        min: 6,
    },
    password: {
        type: String,
        required: true,
        max: 1024,
        min: 8
    },
    profile_pic_url: {
        type: String,
    },
    date: {
        type: Date,
        default: Date.now
    },
    deck_ids: [{
        type: mongoose.ObjectId,
        _id: {
            required: false
        },
    }],
});

// export the schema as 'UserSchema' and all its information so that the controller can import it as 'Users'
module.exports = mongoose.model('User', UserSchema);